const sampledata = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60",
    price: 1500,
    location: "Malibu",
    country: "United States",
    
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60",
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Desert Oasis Villa",
    description: "Find peace in this luxurious desert villa, surrounded by beautiful dunes and endless skies.",
    image: "https://images.unsplash.com/photo-1549887534-4b4f18a7bcb1?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Rustic Lakeside Cabin",
    description: "Cozy up by the lake in this rustic cabin, perfect for fishing and evening campfires.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60",
    price: 950,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury City Apartment",
    description: "A sleek and modern apartment with skyline views and all top amenities included.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Countryside Farmhouse",
    description: "Reconnect with nature in this traditional farmhouse surrounded by lush greenery.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=60",
    price: 1100,
    location: "Lancashire",
    country: "United Kingdom",
  },
  {
    title: "Cliffside Ocean View Villa",
    description: "Wake up to breathtaking ocean views from this cliffside villa with private infinity pool.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 4000,
    location: "Phuket",
    country: "Thailand",
  },
  {
    title: "Ski Chalet Escape",
    description: "Perfect winter escape for ski lovers, with cozy fireplace and mountain access.",
    image: "https://images.unsplash.com/photo-1550510537-89d5430d3d9b?auto=format&fit=crop&w=800&q=60",
    price: 1900,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Traditional Japanese Ryokan",
    description: "Experience Japanese culture and hospitality in this peaceful ryokan with tatami rooms.",
    image: "https://images.unsplash.com/photo-1582719478175-2d1c90e9c3c7?auto=format&fit=crop&w=800&q=60",
    price: 1700,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Tropical Island Hut",
    description: "Sleep under the stars in this open-air hut surrounded by palm trees and waves.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60",
    price: 700,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Urban Penthouse Suite",
    description: "Luxury penthouse with panoramic city views and private rooftop terrace.",
    image: "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Toronto",
    country: "Canada",
  },
  {
    title: "Rainforest Bungalow",
    description: "Immerse yourself in nature in this eco-friendly bungalow surrounded by rainforest.",
    image: "https://images.unsplash.com/photo-1613553474370-53a9b32d91e1?auto=format&fit=crop&w=800&q=60",
    price: 1300,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Charming Paris Apartment",
    description: "Stay in a cozy Paris apartment with a view of the Eiffel Tower and nearby cafes.",
    image: "https://images.unsplash.com/photo-1505691723518-36a1cf1d1f86?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Paris",
    country: "France",
  },
  {
    title: "Safari Lodge Adventure",
    description: "Experience wildlife up close in this luxury safari lodge with guided tours.",
    image: "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Nairobi",
    country: "Kenya",
  },
  {
    title: "Vintage Caravan Stay",
    description: "Travel back in time with this colorful retro caravan surrounded by open skies.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 600,
    location: "Melbourne",
    country: "Australia",
  },
  {
    title: "Snowy Log Cabin",
    description: "Cozy winter getaway with a fireplace and snowy mountain view.",
    image: "https://images.unsplash.com/photo-1600585153837-0c6f7b6d7a2e?auto=format&fit=crop&w=800&q=60",
    price: 1250,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Luxury Desert Camp",
    description: "A stunning desert glamping experience with bonfires and starry skies.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
    price: 1600,
    location: "Merzouga",
    country: "Morocco",
  },
  {
    title: "Hilltop Castle Stay",
    description: "Live like royalty in this restored medieval castle overlooking the countryside.",
    image: "https://images.unsplash.com/photo-1566903451132-745cfb0656d4?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Bavaria",
    country: "Germany",
  },
  {
    title: "Modern Glass House",
    description: "Architectural marvel surrounded by greenery with a panoramic view.",
    image: "https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&w=800&q=60",
    price: 3100,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Riverfront Cabin",
    description: "Listen to the sound of flowing water in this peaceful riverside retreat.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=800&q=60",
    price: 900,
    location: "Oregon",
    country: "United States",
  },
  {
    title: "Charming Village House",
    description: "Cozy home in a quiet village with cobblestone streets and traditional charm.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=60",
    price: 1000,
    location: "Seville",
    country: "Spain",
  },
];

module.exports =sampledata;

